import { LiteElement,css,html,property } from '@vandeurenglenn/lite'
import type { Jobs,Users,WorkReport } from '../../types/index.js'
import { api } from '../api/client.js'
import { showToast } from '../helpers/toast.js'
const day=(date:Date)=>date.toISOString().slice(0,10)
const duration=(ms:number)=>`${Math.floor(ms/3_600_000)}u ${Math.round(ms%3_600_000/60_000)}m`
export class ReportsView extends LiteElement{
 @property({type:Object,consumes:true}) accessor jobs:Jobs={};@property({type:Object,consumes:true}) accessor users:Users={};@property({type:String}) accessor from=day(new Date(new Date().getFullYear(),new Date().getMonth(),1));@property({type:String}) accessor to=day(new Date());@property({type:Object}) accessor report:WorkReport|undefined;@property({type:Boolean}) accessor loading=false
 connectedCallback(){super.connectedCallback();void this.load()}
 async load(){this.loading=true;try{const end=new Date(`${this.to}T23:59:59.999`);this.report=await api.getHoursReport(new Date(`${this.from}T00:00:00`).toISOString(),end.toISOString())}catch(error){console.error(error);showToast('Rapport kon niet geladen worden.')}finally{this.loading=false}}
 get totals(){const map=new Map<string,number>();for(const row of this.report?.rows||[])map.set(row.userId,(map.get(row.userId)||0)+row.duration);return [...map.entries()].sort((a,b)=>b[1]-a[1])}
 exportCsv(){const header=['Medewerker','Job','Check-in','Checkout','Duur uren','Afwijking'];const rows=(this.report?.rows||[]).map(row=>[this.users[row.userId]?.name||row.userId,this.jobs[row.jobId]?.name||row.jobId,new Date(row.checkin).toLocaleString('nl-BE'),row.checkout?new Date(row.checkout).toLocaleString('nl-BE'):'Open',(row.duration/3_600_000).toFixed(2),row.unusual?'Meer dan 12u':row.future?'Toekomstige tijd':'']);const csv=[header,...rows].map(line=>line.map(value=>`"${String(value).replaceAll('"','""')}"`).join(';')).join('\n');const url=URL.createObjectURL(new Blob([`\ufeff${csv}`],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`keepit-uren-${this.from}-${this.to}.csv`;link.click();URL.revokeObjectURL(url)}
 afterRender(){const filters=this.shadowRoot?.querySelector('.filters');if(!filters||filters.querySelector('.pdf-export'))return;const button=document.createElement('button');button.className='pdf-export';button.textContent='PDF / afdrukken';button.disabled=!this.report?.rows.length;button.addEventListener('click',()=>window.print());filters.append(button)}
 static styles=[css`:host{display:flex;flex-direction:column;width:100%;max-width:1100px;gap:16px;padding:22px;box-sizing:border-box}h1,h2,p{margin:0}.head,.panel{padding:18px;border:1px solid var(--app-border);border-radius:var(--app-radius-panel);background:var(--app-panel);box-shadow:var(--app-shadow-soft)}.head{display:flex;justify-content:space-between;gap:16px;align-items:center}.head h1{font-size:1.65rem;font-weight:600}.head p{margin-top:5px;color:var(--md-sys-color-on-surface-variant);font-size:.8rem}.filters{display:flex;gap:8px;align-items:end}.filters label{display:flex;flex-direction:column;gap:5px;color:var(--md-sys-color-on-surface-variant);font-size:.68rem}.filters input,.filters button{height:40px;padding:0 10px;border:1px solid var(--app-border);border-radius:var(--app-radius-control);background:var(--app-panel-strong);color:inherit;font:inherit}.filters button{cursor:pointer}.filters .primary{background:var(--app-accent);color:var(--md-sys-color-on-primary)}.totals{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.total{padding:12px;border:1px solid var(--app-border);border-radius:var(--app-radius-control)}.total strong,.total span{display:block}.total strong{font-size:.85rem}.total span{margin-top:4px;color:var(--app-accent);font-size:1.05rem}.table{overflow:auto}.row{display:grid;grid-template-columns:1fr 1fr 170px 85px;gap:10px;padding:10px 0;border-bottom:1px solid var(--app-border);font-size:.75rem}.row:last-child{border:0}.warning{color:#e69a38}.empty{padding:30px;text-align:center;color:var(--md-sys-color-on-surface-variant)}@media(max-width:700px){:host{padding:12px}.head{align-items:stretch;flex-direction:column}.filters{display:grid;grid-template-columns:1fr 1fr}.filters button{grid-column:auto}.totals{grid-template-columns:1fr}.row{grid-template-columns:1fr auto}.row .date{grid-column:1}.row .time{grid-column:2;grid-row:1}.row .job{grid-column:1}.row .flag{grid-column:2}}`]
 render(){return html`<header class="head"><div><h1>Urenrapport</h1><p>Controleer uren per medewerker en exporteer naar CSV.</p></div><div class="filters"><label>Van<input type="date" .value=${this.from} @input=${(e:Event)=>(this.from=(e.target as HTMLInputElement).value)} /></label><label>Tot<input type="date" .value=${this.to} @input=${(e:Event)=>(this.to=(e.target as HTMLInputElement).value)} /></label><button class="primary" @click=${()=>this.load()}>Tonen</button><button ?disabled=${!this.report?.rows.length} @click=${()=>this.exportCsv()}>CSV</button></div></header><section class="panel"><h2>Per medewerker</h2><div class="totals">${this.totals.map(([id,total])=>html`<article class="total"><strong>${this.users[id]?.name||this.users[id]?.email||id}</strong><span>${duration(total)}</span></article>`)}</div></section><section class="panel table" aria-busy=${this.loading}>${this.loading?html`<div class="empty">Rapport laden…</div>`:this.report?.rows.length?this.report.rows.map(row=>html`<article class="row"><span class="date">${this.users[row.userId]?.name||row.userId}<br/><small>${new Date(row.checkin).toLocaleString('nl-BE')}</small></span><span class="job">${this.jobs[row.jobId]?.name||'Onbekende job'}</span><span class="flag ${row.unusual||row.future?'warning':''}">${row.unusual?'Meer dan 12u':row.future?'Toekomstige tijd':'Normaal'}</span><strong class="time">${duration(row.duration)}</strong></article>`):html`<div class="empty">Geen uren in deze periode.</div>`}</section>`}
}
customElements.define('reports-view',ReportsView)
