import { LiteElement, css, html, property } from '@vandeurenglenn/lite'
import '@vandeurenglenn/lite-elements/icon.js'
import type { Jobs } from '../../types/index.js'
import { getOfflineActions, retryOfflineActions, type OfflineAction } from '../helpers/offline-actions.js'
import { showToast } from '../helpers/toast.js'

export class SyncView extends LiteElement {
  @property({type:Object,consumes:true}) accessor jobs:Jobs={}
  @property({type:Array}) accessor actions:OfflineAction[]=[]
  @property({type:Boolean}) accessor retrying=false
  listener=(event:Event)=>{this.actions=(event as CustomEvent).detail?.actions||getOfflineActions()}
  connectedCallback(){super.connectedCallback();this.actions=getOfflineActions();window.addEventListener('keepit-sync-status',this.listener)}
  disconnectedCallback(){window.removeEventListener('keepit-sync-status',this.listener);super.disconnectedCallback()}
  async retry(){this.retrying=true;await retryOfflineActions();this.actions=getOfflineActions();this.retrying=false;showToast(this.actions.length?'Niet alles kon synchroniseren.':'Alle registraties zijn gesynchroniseerd.')}
  static styles=[css`:host{display:flex;flex-direction:column;width:100%;max-width:900px;gap:16px;padding:22px;box-sizing:border-box}h1,p{margin:0}.head,.panel{border:1px solid var(--app-border);border-radius:var(--app-radius-panel);background:var(--app-panel);box-shadow:var(--app-shadow-soft)}.head{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px 20px}.head h1{font-size:1.65rem;font-weight:600}.head p{margin-top:5px;color:var(--md-sys-color-on-surface-variant);font-size:.8rem}.retry{min-height:42px;padding:0 14px;border:1px solid var(--app-accent-strong);border-radius:var(--app-radius-control);background:var(--app-accent);color:var(--md-sys-color-on-primary);font:inherit;font-weight:600;cursor:pointer}.panel{display:flex;flex-direction:column;gap:8px;padding:18px}.row{display:grid;grid-template-columns:42px minmax(0,1fr) auto;gap:11px;align-items:center;padding:11px;border:1px solid var(--app-border);border-radius:var(--app-radius-control)}.icon{display:grid;place-items:center;width:42px;height:42px;border-radius:var(--app-radius-control);background:var(--app-accent-soft);color:var(--app-accent)}.copy strong,.copy span{display:block}.copy strong{font-size:.82rem}.copy span{margin-top:4px;color:var(--md-sys-color-on-surface-variant);font-size:.7rem}.state{color:#e69a38;font-size:.7rem}.empty{padding:38px;color:var(--md-sys-color-on-surface-variant);text-align:center}@media(max-width:600px){:host{padding:12px}.head{padding:14px}.retry{width:42px;padding:0;font-size:0}.retry::after{content:'↻';font-size:20px}.row{grid-template-columns:38px minmax(0,1fr)}.state{grid-column:2}}`]
  render(){return html`<header class="head"><div><h1>Synchronisatie</h1><p>Offline geregistreerde werkuren worden in volgorde verwerkt.</p></div><button class="retry" ?disabled=${this.retrying||!this.actions.length||!navigator.onLine} @click=${()=>this.retry()}>${this.retrying?'Bezig…':'Opnieuw proberen'}</button></header><section class="panel" aria-live="polite">${this.actions.length?this.actions.map(action=>html`<article class="row"><span class="icon"><custom-icon icon=${action.type==='checkin'?'login':'logout'}></custom-icon></span><div class="copy"><strong>${action.type==='checkin'?'Start':'Stop'} · ${this.jobs[action.job]?.name||'Onbekende job'}</strong><span>${new Date(action.timestamp).toLocaleString('nl-BE')} · opgeslagen ${new Date(action.createdAt).toLocaleString('nl-BE')}</span></div><span class="state">${action.lastError?`Mislukt (${action.attempts||1}×)`:navigator.onLine?'Wacht op verwerking':'Offline bewaard'}</span></article>`):html`<div class="empty">Alles is gesynchroniseerd.</div>`}</section>`}
}
customElements.define('sync-view',SyncView)
