#!/usr/bin/env node

import { readdir } from 'fs/promises'
import { basename, resolve } from 'path'
import { spawnSync } from 'child_process'

const rootDir = process.cwd()
const snapshotDir = resolve(rootDir, 'catalog-snapshots')
const releaseTag = 'catalog-snapshots'

const run = (command, args, options = {}) => {
  const result = spawnSync(command, args, { cwd: rootDir, stdio: 'inherit', ...options })
  if (result.error) throw result.error
  if (result.status !== 0) process.exit(result.status ?? 1)
  return result
}

const listSnapshots = async () => {
  try {
    return (await readdir(snapshotDir)).filter((name) => /^catalog-snapshot-.*\.zip$/i.test(name))
  } catch (error) {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT') return []
    throw error
  }
}

const main = async () => {
  const existingSnapshots = new Set(await listSnapshots())
  run(process.execPath, ['./scripts/catalog-snapshot.mjs'])

  const archiveName = (await listSnapshots()).find((name) => !existingSnapshots.has(name))
  if (!archiveName) throw new Error('Snapshot was created, but its archive could not be identified.')

  const archivePath = resolve(snapshotDir, archiveName)
  const release = spawnSync('gh', ['release', 'view', releaseTag, '--json', 'tagName'], {
    cwd: rootDir,
    stdio: 'ignore'
  })

  if (release.error) throw release.error

  if (release.status === 0) {
    run('gh', ['release', 'upload', releaseTag, archivePath])
  } else {
    run('gh', [
      'release',
      'create',
      releaseTag,
      archivePath,
      '--title',
      'Catalog snapshots',
      '--notes',
      'Catalog backup archives generated by Keepit.',
      '--latest=false'
    ])
  }

  console.log(`Published ${basename(archivePath)} to GitHub Release ${releaseTag}.`)
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
